<?php

namespace BenTools\PusherBundle\Repository;
use BenTools\PusherBundle\Entity\Recipient;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipientRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * @param $user
     * @return array|Recipient[]
     */
    public function findRecipientsForUser($user) {
        if (!is_object($user)) {
            throw new \InvalidArgumentException('$user should be an object.');
        }
        $userClass = get_class($user);
        if (!is_callable([$user, 'getId'])) {
            throw new \InvalidArgumentException(sprintf('%s should have a getId() method.', $userClass));
        }

        return $this->findBy([
            'userClass' => $userClass,
            'userId'    => $user->getId(),
            'active'    => true,
        ]);
    }

}
